# fly.toml app configuration file generated for proyecto-front-az1mpg on 2025-08-16T04:17:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'proyecto-front-az1mpg'
primary_region = 'gdl'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
